server:
  port: 9090
spring:
  application:
    name: spring-cloud-alibaba-dubbo-provider

dubbo:
  application:
    name: spring-cloud-alibaba-dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: N/A